name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Run tests
      run: npm test "../src/test"